# Generated by Django 5.1.6 on 2025-07-24 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DailyReport', '0002_section_progressitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='project_name',
        ),
        migrations.AddField(
            model_name='section',
            name='project',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='DailyReport.projectaccess'),
            preserve_default=False,
        ),
    ]
